import React from 'react'

export const Services = () => {
  return (
    <div>

        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus a sequi consequuntur eveniet veritatis? Quas ab veritatis vero incidunt quaerat cum reprehenderit perspiciatis explicabo tempora in ipsa velit error, quia sint praesentium itaque. Modi ducimus inventore ipsa fuga quaerat possimus. Illum, aliquid delectus. Maiores perferendis corrupti debitis fuga recusandae? Optio adipisci assumenda voluptas enim, nesciunt eum repellat iusto cumque soluta. Dicta necessitatibus eius laborum amet animi velit placeat nemo, possimus modi alias, iste eligendi dolorem? Itaque esse adipisci minima similique, fuga iure enim veniam ut beatae asperiores quia excepturi, cumque hic quibusdam quae rerum totam dolorum dolor, laboriosam eveniet animi.</div><br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus a sequi consequuntur eveniet veritatis? Quas ab veritatis vero incidunt quaerat cum reprehenderit perspiciatis explicabo tempora in ipsa velit error, quia sint praesentium itaque. Modi ducimus inventore ipsa fuga quaerat possimus. Illum, aliquid delectus. Maiores perferendis corrupti debitis fuga recusandae? Optio adipisci assumenda voluptas enim, nesciunt eum repellat iusto cumque soluta. Dicta necessitatibus eius laborum amet animi velit placeat nemo, possimus modi alias, iste eligendi dolorem? Itaque esse adipisci minima similique, fuga iure enim veniam ut beatae asperiores quia excepturi, cumque hic quibusdam quae rerum totam dolorum dolor, laboriosam eveniet animi.</div><br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus a sequi consequuntur eveniet veritatis? Quas ab veritatis vero incidunt quaerat cum reprehenderit perspiciatis explicabo tempora in ipsa velit error, quia sint praesentium itaque. Modi ducimus inventore ipsa fuga quaerat possimus. Illum, aliquid delectus. Maiores perferendis corrupti debitis fuga recusandae? Optio adipisci assumenda voluptas enim, nesciunt eum repellat iusto cumque soluta. Dicta necessitatibus eius laborum amet animi velit placeat nemo, possimus modi alias, iste eligendi dolorem? Itaque esse adipisci minima similique, fuga iure enim veniam ut beatae asperiores quia excepturi, cumque hic quibusdam quae rerum totam dolorum dolor, laboriosam eveniet animi.</div><br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus a sequi consequuntur eveniet veritatis? Quas ab veritatis vero incidunt quaerat cum reprehenderit perspiciatis explicabo tempora in ipsa velit error, quia sint praesentium itaque. Modi ducimus inventore ipsa fuga quaerat possimus. Illum, aliquid delectus. Maiores perferendis corrupti debitis fuga recusandae? Optio adipisci assumenda voluptas enim, nesciunt eum repellat iusto cumque soluta. Dicta necessitatibus eius laborum amet animi velit placeat nemo, possimus modi alias, iste eligendi dolorem? Itaque esse adipisci minima similique, fuga iure enim veniam ut beatae asperiores quia excepturi, cumque hic quibusdam quae rerum totam dolorum dolor, laboriosam eveniet animi.</div><br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus a sequi consequuntur eveniet veritatis? Quas ab veritatis vero incidunt quaerat cum reprehenderit perspiciatis explicabo tempora in ipsa velit error, quia sint praesentium itaque. Modi ducimus inventore ipsa fuga quaerat possimus. Illum, aliquid delectus. Maiores perferendis corrupti debitis fuga recusandae? Optio adipisci assumenda voluptas enim, nesciunt eum repellat iusto cumque soluta. Dicta necessitatibus eius laborum amet animi velit placeat nemo, possimus modi alias, iste eligendi dolorem? Itaque esse adipisci minima similique, fuga iure enim veniam ut beatae asperiores quia excepturi, cumque hic quibusdam quae rerum totam dolorum dolor, laboriosam eveniet animi.</div><br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus a sequi consequuntur eveniet veritatis? Quas ab veritatis vero incidunt quaerat cum reprehenderit perspiciatis explicabo tempora in ipsa velit error, quia sint praesentium itaque. Modi ducimus inventore ipsa fuga quaerat possimus. Illum, aliquid delectus. Maiores perferendis corrupti debitis fuga recusandae? Optio adipisci assumenda voluptas enim, nesciunt eum repellat iusto cumque soluta. Dicta necessitatibus eius laborum amet animi velit placeat nemo, possimus modi alias, iste eligendi dolorem? Itaque esse adipisci minima similique, fuga iure enim veniam ut beatae asperiores quia excepturi, cumque hic quibusdam quae rerum totam dolorum dolor, laboriosam eveniet animi.</div><br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus a sequi consequuntur eveniet veritatis? Quas ab veritatis vero incidunt quaerat cum reprehenderit perspiciatis explicabo tempora in ipsa velit error, quia sint praesentium itaque. Modi ducimus inventore ipsa fuga quaerat possimus. Illum, aliquid delectus. Maiores perferendis corrupti debitis fuga recusandae? Optio adipisci assumenda voluptas enim, nesciunt eum repellat iusto cumque soluta. Dicta necessitatibus eius laborum amet animi velit placeat nemo, possimus modi alias, iste eligendi dolorem? Itaque esse adipisci minima similique, fuga iure enim veniam ut beatae asperiores quia excepturi, cumque hic quibusdam quae rerum totam dolorum dolor, laboriosam eveniet animi.</div><br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus a sequi consequuntur eveniet veritatis? Quas ab veritatis vero incidunt quaerat cum reprehenderit perspiciatis explicabo tempora in ipsa velit error, quia sint praesentium itaque. Modi ducimus inventore ipsa fuga quaerat possimus. Illum, aliquid delectus. Maiores perferendis corrupti debitis fuga recusandae? Optio adipisci assumenda voluptas enim, nesciunt eum repellat iusto cumque soluta. Dicta necessitatibus eius laborum amet animi velit placeat nemo, possimus modi alias, iste eligendi dolorem? Itaque esse adipisci minima similique, fuga iure enim veniam ut beatae asperiores quia excepturi, cumque hic quibusdam quae rerum totam dolorum dolor, laboriosam eveniet animi.</div><br />

    </div>
  )
}
